# Generated by Django 5.2.4 on 2025-07-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcha', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
