# Generated by Django 5.2.4 on 2025-07-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcha', '0003_alter_brand_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributekey',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='value',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='categorygroup',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
