# Generated by Django 5.2.4 on 2025-07-26 09:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olcha', '0004_alter_attributekey_key_alter_attributevalue_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'product')},
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='guest_session_key',
        ),
    ]
